_BASE_: "../../base-prompt.yaml" # applied original version of base-prompt here
RUN_N_TIMES: 1
DATA:
  NAME: "vtab-svhn"
  DATAPATH: "local_datasets/vtab-1k"  # TODO: need to specify here
  NUMBER_CLASSES: 10
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001