_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "StanfordCars"
  DATAPATH: "local_datasets/stanford_cars"  #TODO: need to specify here
  NUMBER_CLASSES: 196
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
