_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "OxfordFlowers"
  DATAPATH: "local_datasets/flowers"  #TODO: need to specify here
  NUMBER_CLASSES: 102
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 50.0
  WEIGHT_DECAY: 0.001