_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "nabirds"
  DATAPATH: "local_datasets/nabirds/nabirds"  #TODO: need to specify here
  NUMBER_CLASSES: 555
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 50.0
  WEIGHT_DECAY: 0.0001